name: pedantic_mono
description: "[mono edition] How to get the most value from Dart static analysis."
version: 1.10.0+4
homepage: https://github.com/mono0926/pedantic_mono

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  pedantic: ">=1.9.0 <2.0.0"